name: Continuous integration

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - nightly

          # Minimum supported version.
          # Keep this in sync with Cargo.toml and README.md
          - 1.59.0

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rust-src, rustfmt, clippy
          target: riscv32imac-unknown-none-elf

      - name: Setup QEMU for RISC-V
        run: sudo apt-get update && sudo apt-get install -y qemu-system-misc

      - name: Setup QEMU for i686
        if: ${{ matrix.rust == 'nightly' }}
        run: sudo apt-get install -y qemu-system-x86

      - name: Build (without testing) as x86_64
        if: ${{ matrix.rust == 'nightly' }} # Tier 2 (precompiled libcore in rustup) since 1.62
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target x86_64-unknown-none

      - name: Build and test as i686
        if: ${{ matrix.rust == 'nightly' }}
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --target i686-unknown-none.json

      - name: Build and test as RISC-V
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target riscv32imac-unknown-none-elf --no-default-features

      - name: Rustfmt
        if: ${{ matrix.rust == 'nightly' }}
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Clippy
        if: ${{ matrix.rust == 'nightly' }}
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
